basic:
    name: 'https://www.brainloop.com/en-gb/'
    environments:
        production: 'https://www.brainloop.com/en-gb/'
        staging: 'https://diligent-brainloop.netlify.app/en-gb'
        development: ''
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - /
        - /solutions/brainloop-meetingsuite
        - /solutions/brainloop-boardroom
        - /solutions/brainloop-dealroom
        - /solutions/brainloop-collaborationroom
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: ''
    sensitivity: 15
    night_mode: ''
    retina_images: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
proxy: false
type: single-site
